[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
changelog_config = "cliff.toml"
# dependencies_update = true # update dependencies with `cargo update`
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_allow_dirty = true # add `--allow-dirty` to `cargo publish`
semver_check = false # disable API breaking changes checks
publish_timeout = "10m" # set a timeout for `cargo publish`
# release_commits = "^feat:" # prepare release only if at least one commit matches a regex

