[package]
name = "aarty"
version = "0.4.9"
edition = "2021"
authors = ["Anas Elgarhy <anas.elgarhy.dev@gmail.com>"]
description = "A simple CLI tool to convert the images to ASCII art"
repository = "https://github.com/anas-elgarhy/aarty"
license = "MIT"
readme = "README.md"
keywords = [
    "ascii",
    "art",
    "image",
    "cli"
]
categories = [
    "command-line-utilities",
    "multimedia",
    "text-processing"
]
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "CHANGELOG.md"
]
exclude = ["images/*"]


[[bin]]
name = "aarty"
path = "src/bin/aarty/main.rs"

[dependencies]
colored = "2.0.4"
image = "0.24.7"
log = "0.4.20"
pretty_env_logger = "0.5.0"
serde ={ version = "1", features = ["derive"], optional = true }

[features]
default = ["colors", "reverse", "serde"]
colors = []
reverse = []
