[package]
name = "aarty"
version = "0.1.0"
edition = "2021"
authors = ["Anas Elgarhy <anas.elgarhy.dev@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.8-rc.3", features = ["derive"] }
colored = "2.0.0"
image = "0.24.4"
