[package]
name = "aarty"
version = "0.4.9"
edition = "2021"
authors = ["Anas Elgarhy <anas.elgarhy.dev@gmail.com>"]
description = "A simple CLI tool to convert the images to ASCII art"
repository = "https://github.com/anas-elgarhy/aarty"
license = "MIT"
readme = "README.md"
autobins = false
keywords = [
    "ascii",
    "art",
    "image",
    "cli"
]
categories = [
    "command-line-utilities",
    "multimedia",
    "text-processing"
]
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "CHANGELOG.md"
]
exclude = ["images/*"]


[[bin]]
name = "aarty"
path = "src/bin/main.rs"

[dependencies]
image = { version = "0.24", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = ["colors", "reverse", "image"]
colors = []
reverse = []
impl_serde = ["serde", "_no_ref"]
_no_ref = []
