# configuration for https://github.com/crate-ci/committed

# https://www.conventionalcommits.org
style="conventional"
allowed_types = [
    "fix",
    "feat",
    "chore",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
    "ci",
]
# allow merge commits
merge_commit = true
# subject is not required to be capitalized
subject_capitalized = false
# subject should start with an imperative verb
imperative_subject = true
# subject should not end with a punctuation
subject_not_punctuated = true
# disable line length
line_length = 0
# disable subject length
subject_length = 0
# Ignore the following authors
ignore_author_re="(dependabot|renovate)"
